sudo: true
dist: trusty
rvm: 2.4.0
cache:
  bundler: true
  directories:
  - vendor/bundle
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - ca-certificates
stages:
  - name: Test
    if: sender != imgbot[bot]
  - name: imgbot
    if: sender = imgbot[bot]
  - name: Run build
    if: branch = master AND sender != imgbot[bot] AND type = push
jobs:
  include:
    - &test-baseline
      stage: Test
      script:
        bundle exec rake
      
    - <<: *test-baseline
      script:
        bundle exec rake external
      if: type IN (pull_request, cron)
    
    - stage: imgbot
      script:
        bundle exec rake verify
    
    - stage: Run build
      env: 
        NEXT_BUILD_TAG=latest
      before_install:
        pip install --user pathlib
      script:
      - if [ "$TRAVIS_TAG" != "" ]; then 
            NEXT_BUILD_TAG=`date +"%m-%d-%Y"`; 
        fi
      - echo ".git" > .dockerignore
      - bundle exec rake docker:build
      - if [ "$NEXT_BUILD_TAG" != "latest" ]; then 
            docker tag acceptbitcoincash/acceptbitcoincash acceptbitcoincash/acceptbitcoincash:"$NEXT_BUILD_TAG"; 
        fi
      deploy:
      - provider: script
        skip-cleanup: true
        script:
        # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker push acceptbitcoincash/acceptbitcoincash
        on: 
          branch: master
          tags: true
          condition: $NEXT_BUILD_TAG != "latest"
      - provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
        fqdn: beta.acceptbitco.in
        keep-history: true
        repo: acceptbitcoincash/acceptbitcoincash
        target_branch: gh-pages
        on: 
          branch: master
  allow_failures:
    script:
      bundle exec rake external
notifications:
  webhooks: http://requestbin.fullcontact.com/1kvushz1
